### ISSUE TITLE
Receiving several issues

### ISSUE THREAD

**Issue by edwinhoekman** [liambaloh/SEPA-XML-Parser#2]
Hi when parsing the contents of the XML into the box and i press submit i get the following error messages:

Warning: Attempt to read property "InstdAmt" on null in C:\xampp\htdocs\sepa\index.php on line 48
Warning: Attempt to read property "Id" on null in C:\xampp\htdocs\sepa\index.php on line 49
Warning: Attempt to read property "IBAN" on null in C:\xampp\htdocs\sepa\index.php on line 49
Warning: Attempt to read property "Cd" on null in C:\xampp\htdocs\sepa\index.php on line 51
Warning: Attempt to read property "Strd" on null in C:\xampp\htdocs\sepa\index.php on line 52
Warning: Attempt to read property "CdtrRefInf" on null in C:\xampp\htdocs\sepa\index.php on line 52
Warning: Attempt to read property "Ref" on null in C:\xampp\htdocs\sepa\index.php on line 52
Warning: Attempt to read property "Ref" on null in C:\xampp\htdocs\sepa\index.php on line 52

I have anonymized the XML and added it to this issue:
[Sepa_betaalbestand_2022_06_22.zip](https://github.com/liambaloh/SEPA-XML-Parser/files/8956721/Sepa_betaalbestand_2022_06_22.zip)

**Comment by liambaloh** [comment]
Hello! Thanks for sending this - I recently deleted an issue with an attached zip as it looked suspicious. Apologies if that was yours. I've looked into it and the errors came from the XML expecting certain XML elements to be there, which wasn't at all a guarantee as per the SEPA XML standard. I've done a pass through the code and updated it so the values aren't required for the program to work, and also exposed some more values. The provided example SEPA XML now passes. Please pull the update and give it a go with the actual SEPA XML and let me know how it goes. Hopefully this fixes it but if there's any other issues, of if you'd like any other values exposed, please let me know! Thanks!

Fixed in efdf1b718f094a5966052152fb02d2856591ffe4

**Comment by edwinhoekman** [comment]
Hi Liam,
This seems to do the trick.
May I also suggest to add the following Value?
<Ustrd>Description 1</Ustrd>
Thanks

**Comment by liambaloh** [comment]
Sure, done in ab8f14fdc2e666b89418f71f95ade6d981ba9cab
